import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import ContactEmail from '@/components/ContactEmail';

export const metadata: Metadata = {
  title: 'Terms — Daybreak',
  description: 'The terms that cover your use of Daybreak.',
};

export default function Terms() {
  return (
    <div className="ht-page">
      <header className="ht-header">
        <Link href="/" className="ht-brand">
          <Image
            src="/daybreak-icon.png"
            alt=""
            width={22}
            height={22}
            className="ht-brand-icon"
            aria-hidden="true"
          />
          Daybreak
        </Link>
        <nav className="ht-nav">
          <Link href="/login">Log in</Link>
        </nav>
      </header>

      <main className="ht-main">
        <h1 className="ht-h1">Terms of Service</h1>
        <p className="ht-updated">Last updated: May 29, 2026</p>

        <div className="ht-legal">
          <section>
            <h2>Agreement to terms</h2>
            <p>
              These terms cover your use of Daybreak. By using the bot or the website at
              daybreak.run, you agree to them. If you don&apos;t, don&apos;t use Daybreak.
            </p>
          </section>

          <section>
            <h2>What Daybreak is</h2>
            <p>
              Daybreak is a running coach you talk to over Telegram. It reads your recent
              Strava activity, the training plan you give it, and the check-ins you send,
              and replies with daily training guidance. The guidance is generated by an AI
              model, so treat it as a coach&apos;s suggestion rather than a fixed
              prescription.
            </p>
          </section>

          <section>
            <h2>Eligibility and access</h2>
            <p>
              Daybreak is invite-only right now. You need a Telegram account to use it, and
              you must be at least 18. You&apos;re responsible for what happens on your
              account, so keep your Telegram login secure.
            </p>
          </section>

          <section>
            <h2>Not medical advice</h2>
            <p>
              Daybreak gives training suggestions. It is not medical advice and not a
              substitute for a doctor, physical therapist, or other professional. You train
              at your own risk. If something hurts, or you have a condition that running
              could affect, stop and talk to a professional before you keep going.
            </p>
          </section>

          <section>
            <h2>Acceptable use</h2>
            <p>You agree not to:</p>
            <ul>
              <li>Use Daybreak for anything unlawful.</li>
              <li>Try to access another athlete&apos;s data or interfere with the service.</li>
              <li>Resell or redistribute the service.</li>
            </ul>
          </section>

          <section>
            <h2>Strava connection</h2>
            <p>
              Connecting Strava is required, and you grant Daybreak read-only access to your
              activities. Daybreak never posts to Strava and never changes anything in your
              account. You can disconnect anytime by sending{' '}
              <code>/disconnect_strava</code> to the bot, or by revoking access from Strava
              (Settings → My Apps). We&apos;re not responsible for changes Strava makes to
              its own API or policies.
            </p>
          </section>

          <section>
            <h2>Your content</h2>
            <p>
              You keep ownership of the training plan and the messages you send. You give
              Daybreak the rights it needs to store and process that information in order to
              run the service for you.
            </p>
          </section>

          <section>
            <h2>Payment</h2>
            <p>
              Daybreak is free for the first group of friends. After that it moves to
              pay-as-you-go: you add credit up front, and it&apos;s drawn down as you use
              the service. When your balance reaches zero, Daybreak pauses until you top up.
            </p>
          </section>

          <section>
            <h2>Disclaimer of warranties</h2>
            <p>
              Daybreak is provided &quot;as is.&quot; We don&apos;t guarantee that it will
              always be available, or that its guidance will be correct or right for you.
            </p>
          </section>

          <section>
            <h2>Limitation of liability</h2>
            <p>
              To the extent the law allows, Daybreak isn&apos;t liable for indirect or
              consequential damages, for injury, or for loss of data arising from your use of
              the service.
            </p>
          </section>

          <section>
            <h2>Termination</h2>
            <p>
              We can suspend or end your access if you break these terms. You can stop using
              Daybreak whenever you want.
            </p>
          </section>

          <section>
            <h2>Changes to these terms</h2>
            <p>
              We may update these terms as Daybreak changes. If you keep using the service
              after an update, that counts as accepting the new terms.
            </p>
          </section>

          <section>
            <h2>Contact</h2>
            <p>Questions about these terms? Get in touch.</p>
            <ContactEmail />
          </section>
        </div>
      </main>

      <footer className="ht-footer">
        <span>© 2026 Daybreak</span>
        <span className="ht-footer-links">
          <Link href="/privacy">Privacy</Link>
          <Link href="/terms">Terms</Link>
          <Link href="/support">Support</Link>
        </span>
      </footer>
    </div>
  );
}
